apiVersion: apps/v1
kind: StateFulSet
metadata:
  name: mongodb_statefulset
spec:
  serviceName: "mongodb_service"
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resource:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
            value: "mongoadmin"
            - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-secrets
                key: mongodb-password
          volumeMounts:
            - mountPath: /data/db 
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOne"]
        resources:
          requests:
            storage: "1Gi"

---
apiVersion: apps/v1
kind: Service
metadata:
  name: mongodb_service
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017