apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: mohsen1299/catalog:v1
          resource:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
